// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgTTWsK-glLw-uE9otQ-XK66gnScTByU',
    appId: '1:972233888567:web:823380004b43d6516380b2',
    messagingSenderId: '972233888567',
    projectId: 'capstone-app-ba60d',
    authDomain: 'capstone-app-ba60d.firebaseapp.com',
    storageBucket: 'capstone-app-ba60d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-V5Y9F7dErKZmhX1IfqfqzMIs_tRKUwc',
    appId: '1:972233888567:android:48a7023cd4d979d56380b2',
    messagingSenderId: '972233888567',
    projectId: 'capstone-app-ba60d',
    storageBucket: 'capstone-app-ba60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0cCrg5BtrN5nIzbAaZq394hQ6Q7_Lops',
    appId: '1:972233888567:ios:87fad89ba725fbc96380b2',
    messagingSenderId: '972233888567',
    projectId: 'capstone-app-ba60d',
    storageBucket: 'capstone-app-ba60d.appspot.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0cCrg5BtrN5nIzbAaZq394hQ6Q7_Lops',
    appId: '1:972233888567:ios:e6bee2f45868e9e96380b2',
    messagingSenderId: '972233888567',
    projectId: 'capstone-app-ba60d',
    storageBucket: 'capstone-app-ba60d.appspot.com',
    iosBundleId: 'com.example.capstoneApp.RunnerTests',
  );
}
